apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-app-config
data:
  WEATHER_API_KEY: "your_api_key_here"
  WEATHER_API_URL: "http://api.openweathermap.org/data/2.5/weather?q=Montreal&appid=${WEATHER_API_KEY}&units=metric"