apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-app-config
data:
  WEATHER_API_KEY: "affe0b9575fc0978c54a7d91af9483a1"
  WEATHER_API_URL: "http://api.openweathermap.org/data/2.5/weather?q=Montreal&appid=${WEATHER_API_KEY}&units=metric"